version: '3.4'

services:
    publisher_api:
        image: my_publisher_api:latest
        build:
            context: ./publisher_api
            dockerfile: Dockerfile

    worker:
        image: my_worker:latest
        depends_on:
            - 'publisher_api'
        build:
            context: ./worker
            dockerfile: Dockerfile

    rabbitmq: # login guest:guest
        image: rabbitmq:3-management
        hostname: 'rabbitmq'
        labels:
            NAME: 'rabbitmq'
        ports:
            - '4369:4369'
            - '5671:5671'
            - '5672:5672'
            - '25672:25672'
            - '15671:15671'
            - '15672:15672'
