version: '3.8'

networks:
    console-dev:
        driver: bridge

services:
    app:
        image: filecreator:latest
        ##build:
            # context: .
            #dockerfile: ./Dockerfile
        command: ["more", "arguments"]
        working_dir: /app
        volumes:
            - ../../files:/app/details
        # environment:
        #     - name=value
