version: '3.8'

networks:
    console-dev:
        driver: bridge

services:
    app:
        image: filecreator:latest
        ##build:
            # context: .
            #dockerfile: ./Dockerfile
        working_dir: /app
        volumes:
            - ../../files:/app/details
        # networks:
        #     - console-dev
# volumes:
#     files:
