version: '3.8'

networks:
    dockerapi-dev:
        driver: bridge

services:
    web:
        container_name: web
        build:
            context: ..
            dockerfile: ./Dockerfile
        depends_on: [postgres]
        ports:
            - '8080:80'
        networks:
            - dockerapi-dev

    postgres_image:
        container_name: 'postgres'
        image: postgres:latest
        environment:
            # change this for a "real" app!
            POSTGRES_PASSWORD: 'mysecretpassword'
            POSTGRES_USER: 'appuser'
            POSTGES_DB: 'appdb'
        restart: always
        networks:
            - dockerapi-dev
        ports:
            # So we can access the database
            # From a tool like JetBrains Rider
            # Optional for this demo
            - '11433:1433' # TCP
