version: '3.8'

networks:
    dockerapi-dev:
        driver: bridge

services:
    web:
        container_name: web
        build:
            context: ..
            dockerfile: ./Dockerfile
        depends_on: [postgres]
        ports:
            - '8080:80'
        networks:
            - dockerapi-dev

    postgres_image:
        container_name: 'postgres'
        image: postgres:latest
        environment:
            # change this for a "real" app!
            POSTGRES_PASSWORD: '4y7sV96vA9wv46VR'
            POSTGRES_USER: 'postgres_user'
            POSTGES_DB: 'studentdDb'
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - dockerapi-dev
        ports:
            - 5432:5432
    volumes:
        pgdata:
