name: Dotnet Build and Docker Deploy

on:
  push:
    branches: [ main ]
    # paths:
    #   - './src/DockerMinAPI/*'
  workflow_dispatch:

jobs:
  local-dotnet-build:
    uses: ./.github/workflows/dotnet.yml
  docker-deploy:
    needs: local-dotnet-build
    uses: ./.github/workflows/docker-hub.yml
    with: 
      username: ${{ secrets.DOCKER_HUB_USERNAME }}
      token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}