name: Dotnet Build CI

on:
#   push:
#     branches: [ main ]
#     paths:
#       - './src/DockerMinAPI/**/*'
    workflow_dispatch:
    workflow_call:
    
env:
    DOTNET_VERSION: '6.0.x' # set this to the dot net version to use

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./src/DockerMinAPI
        steps:
            - uses: actions/checkout@v3
            - name: Setup .NET
              uses: actions/setup-dotnet@v2
              with:
                  dotnet-version: 6.0.x
            - name: Restore dependencies
              run: dotnet restore
            - name: Build
              run: dotnet build --no-restore
            - name: Test
              run: dotnet test --no-build --verbosity normal
